env:
  DOCKER_IMAGE: "gcr.io/opensourcecoin/radicle-surf-build:8c5e5e90064cb89f5faeedfe2874cbc3efbe260c"
  DOCKER_FILE: .docker/build/Dockerfile

steps:
- label: "Build, lint, test"
  commands:
  - "echo '--- Formatting'"
  - "cargo fmt -- --check"
  - "echo '--- Bestest Practices'"
  - "cargo clippy --all-targets --all-features -- -D warnings"
  - "echo '--- Documentationz'"
  - "cargo doc"
  - "echo '--- Tests'"
  - "cargo test --all"
  agents:
    production: "true"
    platform: "linux"
